import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Receipt, Calendar, CreditCard, ExternalLink, ShieldCheck, Download, AlertTriangle } from 'lucide-react';
import api from '../../utils/api';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

const PaymentHistory = () => {
    const [payments, setPayments] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        fetchPayments();
    }, []);

    const fetchPayments = async () => {
        try {
            setLoading(true);
            const response = await api.get('/api/user/payments');
            setPayments(response.data);
            setError(null);
        } catch (err) {
            console.error("Failed to fetch payments:", err);
            setError("Unable to load payment history. Please check your connection.");
        } finally {
            setLoading(false);
        }
    };

    const downloadReceipt = (payment) => {
        const doc = new jsPDF();
        
        // Header
        doc.setFontSize(22);
        doc.setTextColor(30, 64, 175);
        doc.text("E-CHALLAN SYSTEM", 105, 20, { align: "center" });
        
        doc.setFontSize(14);
        doc.setTextColor(100);
        doc.text("PAYMENT RECEIPT", 105, 30, { align: "center" });
        
        doc.setLineWidth(0.5);
        doc.line(20, 35, 190, 35);

        // Transaction Info
        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.text(`Transaction Reference: ${payment.transaction_ref}`, 20, 50);
        doc.text(`Date: ${payment.date}`, 20, 60);
        doc.text(`Status: SUCCESSFUL`, 20, 70);

        // Table
        doc.autoTable({
            startY: 80,
            head: [['Description', 'Challan ID', 'Amount (INR)']],
            body: [
                ['Traffic Violation Penalty', `#${payment.challan_id}`, `INR ${payment.amount}.00`],
            ],
            theme: 'striped',
            headStyles: { fillColor: [30, 64, 175] }
        });

        // Footer
        const finalY = doc.lastAutoTable.finalY + 20;
        doc.setFontSize(10);
        doc.text("Generated by eChallan Traffic Compliance Portal", 20, finalY);
        doc.text("This is a computer generated receipt and does not require a signature.", 20, finalY + 7);

        doc.save(`Receipt_${payment.transaction_ref}.pdf`);
    };

    if (loading) {
        return (
            <div className="p-6 flex justify-center py-20">
                <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-600"></div>
            </div>
        );
    }

    if (error) {
        return (
            <div className="p-6 max-w-7xl mx-auto text-center py-20">
                <div className="bg-red-50 text-red-600 p-8 rounded-2xl border border-red-100 max-w-md mx-auto">
                    <AlertTriangle className="w-12 h-12 mx-auto mb-4" />
                    <h2 className="text-xl font-bold mb-2">Error Loading Data</h2>
                    <p className="mb-6">{error}</p>
                    <button 
                        onClick={fetchPayments} 
                        className="px-6 py-2 bg-red-600 text-white rounded-lg font-semibold hover:bg-red-700 transition-colors"
                    >
                        Try Again
                    </button>
                </div>
            </div>
        );
    }

    return (
        <div className="p-6 max-w-7xl mx-auto space-y-8">
            <header>
                <h1 className="text-3xl font-bold text-white">Payment History</h1>
                <p className="text-slate-400">Track your completed transactions and receipts</p>
            </header>

            {payments.length === 0 ? (
                <div className="text-center py-20 bg-slate-800/50 rounded-2xl border border-slate-700 shadow-sm">
                    <div className="bg-slate-800 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
                        <Receipt className="w-8 h-8 text-slate-500" />
                    </div>
                    <h3 className="text-xl font-semibold text-white">No payment history available.</h3>
                </div>
            ) : (
                <div className="bg-slate-800/50 rounded-2xl border border-slate-700 shadow-sm overflow-hidden">
                    <div className="overflow-x-auto">
                        <table className="w-full text-left border-collapse">
                            <thead>
                                <tr className="bg-slate-800/80 border-b border-slate-700">
                                    <th className="px-6 py-4 text-xs font-bold text-slate-400 uppercase tracking-wider">Transaction ID</th>
                                    <th className="px-6 py-4 text-xs font-bold text-slate-400 uppercase tracking-wider">Challan ID</th>
                                    <th className="px-6 py-4 text-xs font-bold text-slate-400 uppercase tracking-wider">Violation Type</th>
                                    <th className="px-6 py-4 text-xs font-bold text-slate-400 uppercase tracking-wider">Date</th>
                                    <th className="px-6 py-4 text-xs font-bold text-slate-400 uppercase tracking-wider">Amount</th>
                                    <th className="px-6 py-4 text-xs font-bold text-slate-400 uppercase tracking-wider">Status</th>
                                    <th className="px-6 py-4 text-xs font-bold text-slate-400 uppercase tracking-wider text-right">Action</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-700">
                                {payments.map((p, idx) => (
                                    <motion.tr
                                        key={p.id}
                                        initial={{ opacity: 0, x: -10 }}
                                        animate={{ opacity: 1, x: 0 }}
                                        transition={{ delay: idx * 0.05 }}
                                        className="hover:bg-slate-50/50 transition-colors"
                                    >
                                        <td className="px-6 py-4 font-mono text-sm text-slate-300">{p.transaction_ref}</td>
                                        <td className="px-6 py-4 text-sm text-white font-medium">{p.display_challan_id || `#V-${1000 + p.challan_id}`}</td>
                                        <td className="px-6 py-4 text-sm text-slate-300">{p.violation_type || 'Unknown'}</td>
                                        <td className="px-6 py-4 text-sm text-slate-400">
                                            <div className="flex items-center gap-2">
                                                <Calendar className="w-4 h-4" /> {p.date}
                                            </div>
                                        </td>
                                        <td className="px-6 py-4 text-sm font-bold text-white">₹{p.amount}</td>
                                        <td className="px-6 py-4">
                                            <span className="inline-flex items-center gap-1 text-xs font-bold text-emerald-600 bg-emerald-50 px-2.5 py-1 rounded-full border border-emerald-100">
                                                <ShieldCheck className="w-3 h-3" /> Success
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-right">
                                            <button 
                                                onClick={() => downloadReceipt(p)}
                                                className="p-2 hover:bg-blue-50 text-blue-600 rounded-lg transition-colors"
                                            >
                                                <Download className="w-5 h-5" />
                                            </button>
                                        </td>
                                    </motion.tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            )}
        </div>
    );
};

export default PaymentHistory;
